let canvasW=640;let canvasH=480;let bricks=[];let bullets=[];let washer;const cols=8;const rows=5;let brickW;let brickH;let fireCooldown=0;const FIRE_RATE=12;let score=0;let ball;const MAX_BALL_SPEED=12;
function setup(){createCanvas(canvasW,canvasH);initLevel();}
function initLevel(){bricks=[];brickW=Math.floor(canvasW/cols);brickH=30;for(let r=0;r<rows;r++){for(let c=0;c<cols;c++){let b={x:c*brickW+2,y:50+r*(brickH+4),w:brickW-4,h:brickH,dirty:Math.floor(random(1,4))};bricks.push(b);}}washer={x:canvasW/2,y:canvasH-40,w:80,h:16,speed:6};bullets=[];score=0;fireCooldown=0;ball={x:canvasW/2,y:canvasH-60,r:8,vx:random(-3,3),vy:-6};}
function draw(){background(30);updateWasher();updateBall();updateBullets();drawBricks();drawWasher();drawBall();drawHUD();checkWin();}
function updateWasher(){if(mouseIsPressed){washer.x=constrain(mouseX,washer.w/2,canvasW-washer.w/2);}if(keyIsDown(LEFT_ARROW)){washer.x=Math.max(washer.w/2,washer.x-washer.speed);}if(keyIsDown(RIGHT_ARROW)){washer.x=Math.min(canvasW-washer.w/2,washer.x+washer.speed);}if(fireCooldown>0){fireCooldown--;}if(keyIsDown(32)){if(fireCooldown===0){spawnBullet();fireCooldown=FIRE_RATE;}}}
function spawnBullet(){let b={x:washer.x,y:washer.y-washer.h/2-8,r:6,vy:-8};bullets.push(b);if(bullets.length>200){bullets.splice(0,bullets.length-200);}}
function updateBullets(){for(let i=bullets.length-1;i>=0;i--){let b=bullets[i];b.x+=0;b.y+=b.vy;if(b.y<-20){bullets.splice(i,1);continue;}let hit=false;for(let j=bricks.length-1;j>=0;j--){let br=bricks[j];if(circleRectCollision(b,br)){br.dirty-=1;if(br.dirty<=0){bricks.splice(j,1);score+=10;}bullets.splice(i,1);hit=true;break;}}if(hit){continue;}}}
function updateBall(){if(ball===undefined){return;}ball.x+=ball.vx;ball.y+=ball.vy;if(ball.x-ball.r<0){ball.x=ball.r;ball.vx=Math.abs(ball.vx);}if(ball.x+ball.r>canvasW){ball.x=canvasW-ball.r;ball.vx=-Math.abs(ball.vx);}if(ball.y-ball.r<0){ball.y=ball.r;ball.vy=Math.abs(ball.vy);}if(ball.y-ball.r>canvasH){ball.x=washer.x;ball.y=washer.y-washer.h/2-10;ball.vy=-6;ball.vx=random(-3,3);}let washerRect={x:washer.x-washer.w/2,y:washer.y-washer.h/2,w:washer.w,h:washer.h};if(circleRectCollision(ball,washerRect) && ball.vy>0){ball.y=washerRect.y-ball.r;ball.vy=-Math.abs(ball.vy);let hit=(ball.x-washer.x)/(washer.w/2);ball.vx+=hit*3;if(ball.vx>MAX_BALL_SPEED){ball.vx=MAX_BALL_SPEED;}if(ball.vx<-MAX_BALL_SPEED){ball.vx=-MAX_BALL_SPEED;}}for(let j=bricks.length-1;j>=0;j--){let br=bricks[j];if(circleRectCollision(ball,br)){br.dirty-=1;if(br.dirty<=0){bricks.splice(j,1);score+=10;}ball.vy=-ball.vy;ball.y+=ball.vy;break;}}if(Math.abs(ball.vx)>MAX_BALL_SPEED){ball.vx=Math.sign(ball.vx)*MAX_BALL_SPEED;}if(Math.abs(ball.vy)>MAX_BALL_SPEED){ball.vy=Math.sign(ball.vy)*MAX_BALL_SPEED;}}
function circleRectCollision(c,r){let cx=c.x;let cy=c.y;let rx=r.x;let ry=r.y;let rw=r.w;let rh=r.h;let nearestX=Math.max(rx,Math.min(cx,rx+rw));let nearestY=Math.max(ry,Math.min(cy,ry+rh));let dx=cx-nearestX;let dy=cy-nearestY;return(dx*dx+dy*dy)<=(c.r*c.r);}
function drawBricks(){for(let i=0;i<bricks.length;i++){let b=bricks[i];let t=b.dirty;let col=color(150,100,50);if(t===3){col=color(200,80,40);}else if(t===2){col=color(180,120,60);}else{col=color(120,170,80);}fill(col);rect(b.x,b.y,b.w,b.h,4);fill(255);textSize(12);textAlign(CENTER,CENTER);text(''+b.dirty,b.x+b.w/2,b.y+b.h/2);} }
function drawWasher(){fill(80,160,220);rectMode(CENTER);rect(washer.x,washer.y,washer.w,washer.h,8);rectMode(CORNER);}
function drawBall(){fill(255);noStroke();ellipse(ball.x,ball.y,ball.r*2,ball.r*2);stroke(0,50);}
function drawHUD(){fill(255);textSize(16);textAlign(LEFT,TOP);text('Score: '+score,8,8);text('Bricks: '+bricks.length,8,28);if(bricks.length===0){textAlign(CENTER,CENTER);textSize(32);text('CLEANED!',canvasW/2,canvasH/2);} }
function checkWin(){if(bricks.length===0){if(frameCount%120===0){initLevel();}}}
function keyPressed(){if(key==='r'||key==='R'){initLevel();}if(keyCode===32){if(fireCooldown===0){spawnBullet();fireCooldown=FIRE_RATE;}}}
